"""Added guests column so number of guests buying tickets can be limited

Revision ID: 17e3670cf479
Revises: eea8bbf6d994
Create Date: 2024-11-15 14:42:42.836292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e3670cf479'
down_revision = 'eea8bbf6d994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guests', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('guests')

    # ### end Alembic commands ###
