"""Added a column to indicate if it has been used

Revision ID: 834c779c54d8
Revises: ba4cf3b3d32a
Create Date: 2024-11-16 18:54:20.979389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834c779c54d8'
down_revision = 'ba4cf3b3d32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new column
    op.add_column('tickets', sa.Column('ticket_used', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Backfill the default value for existing rows
    op.execute('UPDATE tickets SET ticket_used = FALSE')

    # Remove server_default after the backfill
    op.alter_column('tickets', 'ticket_used', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('ticket_used')

    # ### end Alembic commands ###
