"""Added stripe key model

Revision ID: b49ba14def83
Revises: 75c9b67b23d1
Create Date: 2024-11-23 17:21:13.674772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49ba14def83'
down_revision = '75c9b67b23d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('private_key', sa.String(length=255), nullable=False))
        batch_op.drop_column('stripe_api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stripe_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_api_key', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('private_key')
        batch_op.drop_column('public_key')

    # ### end Alembic commands ###
