"""Added price attribute to Events

Revision ID: e4d9ac36ab7e
Revises: 17e3670cf479
Create Date: 2024-11-15 21:40:51.962771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d9ac36ab7e'
down_revision = '17e3670cf479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
