"""Add Event model

Revision ID: eea8bbf6d994
Revises: 
Create Date: 2024-11-15 10:24:40.911604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea8bbf6d994'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('event_owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
